Vagrant.configure("2") do |config|

  # ── NorthStar Bank Target Server ──────────────────────────────────────────
  config.vm.define "northstar" do |ns|
    ns.vm.box      = "ubuntu/jammy64"
    ns.vm.hostname = "northstar-bank"

    ns.vm.network "private_network", ip: "192.168.56.30"

    # Forward port 80 to host 8080 for browser access during development
    ns.vm.network "forwarded_port", guest: 80, host: 8080

    ns.vm.provider "virtualbox" do |vb|
      vb.name   = "Lab9-NorthStar"
      vb.memory = 1024
      vb.cpus   = 1
    end

    ns.vm.provision "shell", path: "provision.sh"
  end

end
